version: "3"

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=service
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--bind-address=0.0.0.0"]
  fastapi:
    build: ./backend
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
    ports:
      - "8000:8000"
      # For hot-reload
    volumes:
      - ./backend/app/:/app
      - fastapi_data:/app/__pycache__
    depends_on:
      - db

  react:
    build: ./frontend
    environment:
      - REACT_APP_API_URL=http://fastapi:8000
    ports:
      - "443:3000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - fastapi

volumes:
  db_data:
  fastapi_data:
